image: ldap
org: oldemo
arches:
  - amd64
gitrepo: https://github.com/ObjectifLibre/linuxkit-ldap-demo.git
network: yes
disable-content-trust: yes
config:
  capabilities:
   - CAP_NET_BIND_SERVICE
   - CAP_CHOWN
   - CAP_SETUID
   - CAP_SETGID
   - CAP_DAC_OVERRIDE
